### ISSUE TITLE
Implement auto clean-up of Prometheus PVC

### ISSUE THREAD

**Issue by jurslo** [dNationCloud/ping#10]

**Comment by matofeder** [comment]
Setup already done in private pipeline by custom values.yaml:
```
prometheus:
  server:
    retention: 365d
    extraFlags:
    - storage.tsdb.retention.size=45GB
```
for detail see: https://www.robustperception.io/configuring-prometheus-storage-retention
